Integer x = 5;
Integer y = 6;
Double a = 5.2;
Double b = 6.3;
String foo = "foo";
String bar = "bar";

print( x == 5);
print( x != y);
print( x > y );
print( x < y );
print( x > y + 3);
print( x < y + 2);
print( x >= 5);
print( y >= x);
print( x <= 6);
print( y <= 6);
print( a == 5.2 );
print( a == b );
print( a != b );
print( a < b );
print( a > b );
print( a >= 5.1 );
print( b <= 6.4 );
print( foo == bar );
print( foo != bar );
print( foo > bar );
print( foo < bar );
print( concat( foo, bar ) == "foobar" );