public enum TERMINAL {
    PLUS,MINUS,MULTI,DIVIDE,POWER,
    LESS,LESSEQUAL,GREATER,GREATEREQUAL,EQUAL,NOTEQUAL,
    L_BRACKET,R_BRACKET, R_PAREN, L_PAREN, END,COMMA,
    DOUBLE,INT,STRING,
    D_ID,I_ID,S_ID,ID,
    IF,ELSE,WHILE,FOR,
    PRINT,CONCAT,CHARAT,
    ASSIGN,I_ASMT,D_ASMT,S_ASMT,
    NEWLINE,$
}
